export const items = {
  services: [
    {
      id: 1,
      title: "Custom Screen Printing",
      slug: "custom-screen-printing",
      desc: "Use our custom screen printing service to create an outstanding impression on your customers. We apply vibrant, long-lasting inks to imprint your company's name, images, and messaging onto high-quality textiles. Our state-of-the-art technology guarantees vivid, striking designs that draw in viewers. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards!",
      image: "https://affixapparel.com/image/catalog/screen-printing.jpg",
    },
    {
      id: 2,
      title: "Custom Embroidery",
      slug: "custom-embroidery",
      desc: "Use our custom embroidery to uplift your brand’s sophistication. Our skilled makers precisely stitch your designs into high-quality textiles to give them a plush, textured feel. Elegance blends with precision to guarantee that your clothes convey the outstanding quality that is associated with your brand. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards",
      image: "https://affixapparel.com/image/catalog/custom-embroidery.jpg",
    },
    {
      id: 3,
      title: "All-Over Sublimation Printing",
      slug: "sublimation-printing",
      desc: "With Affix’s all-over sublimation printing, bring out your creativity. We make every square inch of your clothing into a vivid, picture-perfect canvas. Our cutting-edge sublimation technique ensures durable, crisp prints that distinguish your business. Uncover boundless opportunities and create a lasting impact on your clientele.",
      label: "24/7 Support",
      label1: " Fast Delivery",
      label2: "High Standards",
      image: "https://affixapparel.com/image/catalog/sublimation.jpg",
    },
    {
      id: 4,
      title: "Apparel Packaging Bags",
      slug: "packaging-bags",
      desc: "Complete your brand's presentation with our premium apparel packaging bags. Our bags are made to last and look well, adding to your consumers' unboxing experience. Improve the perceived value of your brand with chic packaging that represents Affix Apparel's dedication to quality. ",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards!",
      image: "https://affixapparel.com/image/catalog/apparel-bags.jpg",
    },
    {
      id: 5,
      title: "Custom Neck Gaiter",
      slug: "neck-gaiter",
      desc: "Enhance your style and safeguard yourself with our personalized neck gaiters. Combining versatility and fashion, these accessories provide a customized flair while delivering a snug and pleasant fit for different occasions.",
      label: "24/7 Support",
      label1: "Fast Delivery",
      label2: "High Standards",
      image: "https://affixapparel.com/image/catalog/neck-gaiter.jpg",
    },
    {
      id: 6,
      title: "Custom Socks Manufacturer",
      slug: "custom-socks",
      desc: "Step with style and comfort in our customized socks. Precisely crafted by expert custom apparel manufacturers USA, these socks seamlessly merge superior artistry with personalized designs, turning every walk into a unique expression of individuality.",
      label: "24/7 Support",
      label1: " Fast Delivery",
      label2: "High Standards",
      image: "https://affixapparel.com/image/catalog/Socks-Manufacturer.jpg",
    },
  ],
};
